apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    straw-resource: ""  # Empty value for the straw-resource label
type: Opaque
data:
  username: dXNlcm5hbWU=  # Base64-encoded value for "username"
  password: cGFzc3dvcmQ=  # Base64-encoded value for "password"
