apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cluster1
  labels:
    app: nginx
    hub.transport-informer/target-namespace: default
    hub.transport-informer/resources: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80